### ISSUE TITLE
Should we pin versions here?

### ISSUE THREAD

**Issue by virtuald** [robotpy/robotpy-meta#11]
I sorta like the idea of saying "oh you have robotpy 2023.x.y.z, so you must have this specific set of packages". However, that probably wouldn't work so well with vendor packages since maybe users might want to use an older version for some reason?

Right now, we only bound the minimum version of the package... which is fine, but seems potentially bad.

We could use a different boundary (so like keep it within a minor version?) instead. Open to other options.

Edit: So it seems to me that there are three different options available to us. Let's assume that the current version of wpilib is `2023.1.2.3`. Here are the options:

1) `wpilib<2024.0.0,>=2023.1.2.3` (this is what we do now)
2) `wpilib<2023.2.0,>=2023.1.2.3`
3) `wpilib==2023.1.2.3`

It seems that doing any of those things for wpilib dependencies is fairly reasonable. The tricky part would be vendor libraries.

**Comment by mdurrani808** [comment]
I think best practice for stability would be pinning versions, or bounding to minimum versions with yearly scheduled upgrades before the beta every year.

**Comment by virtuald** [comment]
Currently we bound the versions by year: https://github.com/robotpy/robotpy-meta/blob/main/requirements.txt

**Comment by virtuald** [comment]
Updated description with what I see as the three options we have now.

**Comment by legoguy1000** [comment]
I would agree that I think that pinning is definitely the best thing. It provides the most predictable results.

**Comment by virtuald** [comment]
I have decided to pin allwpilib based packages, and keep vendors in a year-based bounded range.
